name: Vavoo IPTV Proxy
slug: vavoo_proxy
version: "1.0.0"
description: Vavoo IPTV Proxy for TVHeadend
startup: services
boot: auto
host_network: true

options:
  http_port: 8088
  language: de
  region: US

schema:
  http_port: int
  language: str
  region: str
